name: pull_request-workflow
on: pull_request

jobs:
  pull_request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "This is a pull_request workflow"
      - name: step 2
        run: |
          echo "This is pull_request workflow - step 2"
          echo "Running multiple commands"